### PR TITLE
build: Version bump dx to 0.1.0

### PR DESCRIPTION
**Pull request by jnumainville**
Version bump dx to 0.1.0

@mofojed @devinrsmith Are the tokens set properly? I don't think we've pushed a version in this repo yet

### CODE REVIEW

**Comment by mofojed** [comment]
@jnumainville no not yet, we still need the `PYPI_PLOTLY_EXPRESS_TOKEN` to be set; though perhaps it'll just be `DEEPHAVEN_PYPI_TOKEN` instead, and we need to update the token the action uses.
@devinrsmith Can you expose that token to this repo?

**Comment by devinrsmith** [comment]
It's recommended to scope pypi tokens to specific packages instead of the whole user account. Can we get a list of all the PyPi packages that we'll need tokens for?

**Comment by jnumainville** [comment]
@devinrsmith at the moment: plotly-express, plotly, json, matplotlib
ideally in the form PYPI_PLOTLY_EXPRESS_TOKEN, PYPI_PLOTLY_TOKEN, PYPI_JSON_TOKEN, PYPI_MATPLOTLIB_TOKEN

**Comment by devinrsmith** [comment]
I'm going to suggest setting up via:

https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
 https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
 
 This attaches the credentials at the PyPi project level and doesn't need user-level tokens. I've set up trusted publishing for deephaven-plugin-matplotlib and deephaven-plugin-json against this repo and `release-python-package.yml`.

**Comment by jnumainville** [comment]
I've set up plotly-express for trusted publishing. Changes will be made in #84 for full support

**Review by mofojed — CHANGES_REQUESTED** [review]
Pretty sure we need https://github.com/deephaven/deephaven-plugins/pull/84 to merge first, so marking this one as needing changes until that merges.

**Pull request merged**
