### PR TITLE
ci: Migrate docs upload to Google cloud

### LINKED ISSUE #742: Migrate docs from Cloudflare to Google Cloud

### PR DESCRIPTION
**Pull request by jnumainville**
Fixes #742 

I've tested on my own fork

### CODE REVIEW

**Review by mofojed — COMMENTED** [review]
We need these secrets set before merging this I assume. Who's on to set those?

**Comment by jnumainville** [comment]
I will, was just waiting for approval before adding them in case there were changes to names

**Comment by dsmmcken** [comment]
lgtm, not sure the bucket is a secret in this case, as it's a public bucket, but whaterve.

**Comment by jnumainville** [comment]
yeah didn't really think it was but I lean too cautious... much happier to be told that than the other way around!

**Comment by jnumainville** [comment]
I've added the secrets, just need formal approval

**Comment by dsmmcken** [comment]
Anything blocking this or we good?

**Review by mofojed — APPROVED** [review]

**Pull request merged**
